name: Build Game

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install and Set Up Docker
        # You may pin to the exact commit or the version.
        # uses: docker-practice/actions-setup-docker@2d1d86c7fd8177d36a51a328528c79aae2bcb1fe
        uses: docker-practice/actions-setup-docker@v1
      - name: Build image
        run: docker build . -t build-ninelives:latest
      - name: Run build
        run: docker run -v .:/source -v ninelives.pdx:/home/playdate-sdk/ninelives.pdx
